/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f0xx.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	GPIOA->MODER |= GPIO_MODER_MODER5_0;
	//GPIOA->BSRR = (1<<5); // set
	//GPIOA->BRR = (1<<5); // reset
	//GPIOA->ODR ^= (1<<5); // toggle

    /* Loop forever */
/*	for(;;)
	{

		uint8_t pole[32]={1,0,1,0,1,0,0,1,1,1,0,1,1,1,0,1,1,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0};
		for (uint8_t iter = 0; iter < 32; iter++) {


			uint8_t moorse = pole[iter];

			if ( moorse) {
				GPIOA->BSRR = (1<<5);

			} else {
				GPIOA->BRR = (1<<5);

			}

			for (volatile uint32_t i = 0; i < 100000; i++) {}

		}

	}
}
*/

for(;;)
	{

		uint32_t morse=0b10101001110111011100101010000000;
		for (uint8_t iter = 0; iter < 32; iter++) {




			if ( morse & 1<<31) {
				GPIOA->BSRR = (1<<5);

			} else {
				GPIOA->BRR = (1<<5);

			}
			morse = morse<<1;

			for (volatile uint32_t i = 0; i < 100000; i++) {}


		}

	}
}

